controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_elbow_joint
      - r_wrist_1_joint
      - r_wrist_2_joint
      - r_wrist_3_joint
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_elbow_joint
      - l_wrist_1_joint
      - l_wrist_2_joint
      - l_wrist_3_joint
  - name: fake_right_gripper_controller
    joints:
      - r_robotiq_85_left_knuckle_joint
  - name: fake_left_gripper_controller
    joints:
      - l_robotiq_85_left_knuckle_joint